insert into buildings (id, name) values (1, 'Admin Hall');
insert into buildings (id, name) values (2, 'Beckett Building');
insert into buildings (id, name) values (3, 'Chaucer Library');
insert into buildings (id, name) values (4, 'Darwin Science Center');
insert into buildings (id, name) values (5, 'Emerson Arts Pavilion');
insert into buildings (id, name) values (6, 'Faraday Tower');
insert into buildings (id, name) values (7, 'Galileo Hall');
insert into buildings (id, name) values (8, 'Hawking Auditorium');
insert into buildings (id, name) values (9, 'Innovation Hub');
insert into buildings (id, name) values (10, 'Jenner Institute');
insert into buildings (id, name) values (11, 'Kepler Lab Complex');
insert into buildings (id, name) values (12, 'Leonardo Dormitory');
insert into buildings (id, name) values (13, 'Maxwell Gymnasium');
insert into buildings (id, name) values (14, 'Newton Observatory');
insert into buildings (id, name) values (15, 'Orwell Student Union');
insert into buildings (id, name) values (16, 'Pascal Engineering Facility');
insert into buildings (id, name) values (17, 'Quantum Research Building');
insert into buildings (id, name) values (18, 'Rosalind Academic Plaza');
insert into buildings (id, name) values (19, 'Sagan Planetarium');
insert into buildings (id, name) values (20, 'Tesla Innovation Center');
insert into buildings (id, name) values (21, 'Mendel Hall');
insert into buildings (id, name) values (22, 'Curie Institute');
insert into buildings (id, name) values (23, 'Franklin Study Center');
insert into buildings (id, name) values (24, 'Lovelace Lab');
insert into buildings (id, name) values (25, 'Turing Building');
insert into buildings (id, name) values (26, 'Nightingale Hall');
insert into buildings (id, name) values (27, 'Pasteur Pavilion');
insert into buildings (id, name) values (28, 'Goodall Greenhouse');
insert into buildings (id, name) values (29, 'Heisenberg Complex');
insert into buildings (id, name) values (30, 'Meitner Annex');
insert into buildings (id, name) values (31, 'Fermi Facility');
insert into buildings (id, name) values (32, 'Hopper Information Commons');
insert into buildings (id, name) values (33, 'Crick Conference Center');
insert into buildings (id, name) values (34, 'McClintock Tower');
insert into buildings (id, name) values (35, 'Salk Seminar House');
insert into buildings (id, name) values (36, 'Hodgkin Hub');
insert into buildings (id, name) values (37, 'Franklin Study Center');
insert into buildings (id, name) values (38, 'Carson Conservatory');
insert into buildings (id, name) values (39, 'Leakey Library');
insert into buildings (id, name) values (40, 'Planck Workshop');
insert into buildings (id, name) values (41, 'Atlas Pavilion');
insert into buildings (id, name) values (42, 'Babbage Complex');
insert into buildings (id, name) values (43, 'Copernicus Hall');
insert into buildings (id, name) values (44, 'Dalton Chemistry Labs');
insert into buildings (id, name) values (45, 'Euclid Mathematics Building');
insert into buildings (id, name) values (46, 'Fibonacci Tower');
insert into buildings (id, name) values (47, 'Galen Medical Wing');
insert into buildings (id, name) values (48, 'Herodotus Humanities Hall');
insert into buildings (id, name) values (49, 'Icarus Innovation Center');
insert into buildings (id, name) values (50, 'Jansky Observatory');
insert into buildings (id, name) values (51, 'Keppler Conference Center');
insert into buildings (id, name) values (52, 'Lavoisier Science Hall');
insert into buildings (id, name) values (53, 'Mendeleev Research Facility');
insert into buildings (id, name) values (54, 'Nobel Prize Hall');
insert into buildings (id, name) values (55, 'Oppenheimer Physics Labs');
insert into buildings (id, name) values (56, 'Pythagoras Plaza');
insert into buildings (id, name) values (57, 'Quantum Mechanics Institute');
insert into buildings (id, name) values (58, 'Rutherford Atomic Wing');
insert into buildings (id, name) values (59, 'Socrates Debate Arena');
insert into buildings (id, name) values (60, 'Thales Technology Hub');
insert into buildings (id, name) values (61, 'Ulysses Literature Library');
insert into buildings (id, name) values (62, 'Volta Electrical Engineering Building');
insert into buildings (id, name) values (63, 'Watt Engineering Workshop');
insert into buildings (id, name) values (64, 'Xenophon Economics Forum');
insert into buildings (id, name) values (65, 'Young Biotechnology Center');
insert into buildings (id, name) values (66, 'Zeno Philosophy Department');
insert into buildings (id, name) values (67, 'Archimedes Aquatic Center');
insert into buildings (id, name) values (68, 'Bohr Botanical Gardens');
insert into buildings (id, name) values (69, 'Curie Cancer Research Institute');
insert into buildings (id, name) values (70, 'Drake Digital Media Studio');
insert into buildings (id, name) values (71, 'Apollo Archives');
insert into buildings (id, name) values (72, 'Bronte Cultural House');
insert into buildings (id, name) values (73, 'Cervantes Language Center');
insert into buildings (id, name) values (74, 'Descartes Philosophy Hall');
insert into buildings (id, name) values (75, 'Edison Innovation Lab');
insert into buildings (id, name) values (76, 'Fleming Biomedical Labs');
insert into buildings (id, name) values (77, 'Gutenberg Communication Hub');
insert into buildings (id, name) values (78, 'Hypatia Mathematics Institute');
insert into buildings (id, name) values (79, 'Ibsen Theatre Workshop');
insert into buildings (id, name) values (80, 'Joule Physics Department');
insert into buildings (id, name) values (81, 'Klimt Visual Arts Studio');
insert into buildings (id, name) values (82, 'Lovelace Computing Annex');
insert into buildings (id, name) values (83, 'Marconi Wireless Facility');
insert into buildings (id, name) values (84, 'Nightingale Nursing School');
insert into buildings (id, name) values (85, 'Orwellian Studies Building');
insert into buildings (id, name) values (86, 'Ptolemy Astronomy Tower');
insert into buildings (id, name) values (87, 'Quantum Analysis Center');
insert into buildings (id, name) values (88, 'Raman Spectroscopy Lab');
insert into buildings (id, name) values (89, 'Salk Vaccine Research Institute');
insert into buildings (id, name) values (90, 'Thoreau Environmental Studies');
insert into buildings (id, name) values (91, 'Admin Hall');
insert into buildings (id, name) values (92, 'Beckett Building');
insert into buildings (id, name) values (93, 'Chaucer Library');
insert into buildings (id, name) values (94, 'Darwin Science Center');
insert into buildings (id, name) values (95, 'Emerson Arts Pavilion');
insert into buildings (id, name) values (96, 'Faraday Tower');
insert into buildings (id, name) values (97, 'Galileo Hall');
insert into buildings (id, name) values (98, 'Hawking Auditorium');
insert into buildings (id, name) values (99, 'Innovation Hub');
insert into buildings (id, name) values (100, 'Jenner Institute');
