insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (1, 'Anthropology', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (2, 'Biochemistry', 4.5, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (3, 'Cognitive Science', 1.5, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (4, 'Data Analysis', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (5, 'Environmental Science', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (6, 'Finance', 2, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (7, 'Genetics', 2, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (8, 'History', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (9, 'Information Technology', 5, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (10, 'Journalism', 4.5, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (11, 'Kinesiology', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (12, 'Linguistics', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (13, 'Mathematics', 5, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (14, 'Neuroscience', 1.5, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (15, 'Organizational Behavior', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (16, 'Philosophy', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (17, 'Quantum Mechanics', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (18, 'Robotics', 4, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (19, 'Sociology', 4, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (20, 'Theology', 5.5, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (21, 'Urban Planning', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (22, 'Veterinary Science', 1.5, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (23, 'Web Development', 5, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (24, 'Xenobiology', 4, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (25, 'Youth Studies', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (26, 'Zoology', 7, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (27, 'Artificial Intelligence', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (28, 'Business Law', 3, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (29, 'Creative Writing', 3, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (30, 'Digital Marketing', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (31, 'Econometrics', 4, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (32, 'Forensic Science', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (33, 'Graphic Design', 4, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (34, 'Human Resource Management', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (35, 'International Relations', 5.5, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (36, 'Java Programming', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (37, 'Kinematics', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (38, 'Legal Studies', 3.5, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (39, 'Molecular Biology', 4, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (40, 'Nutrition', 4, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (41, 'Operations Research', 4, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (42, 'Political Science', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (43, 'Quantum Computing', 2, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (44, 'Renewable Energy', 4, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (45, 'Software Engineering', 4, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (46, 'Telecommunications', 7, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (47, 'User Experience Design', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (48, 'Visual Arts', 4, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (49, 'Wildlife Conservation', 4, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (50, 'X-ray Crystallography', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (51, 'Accounting', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (52, 'Aeronautical Engineering', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (53, 'African Studies', 3, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (54, 'Agribusiness', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (55, 'American Studies', 7, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (56, 'Animation', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (57, 'Applied Mathematics', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (58, 'Archaeology', 4, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (59, 'Astrophysics', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (60, 'Behavioral Economics', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (61, 'Biomedical Engineering', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (62, 'Botany', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (63, 'Chemical Engineering', 6, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (64, 'Classical Studies', 6, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (65, 'Computational Biology', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (66, 'Conservation Biology', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (67, 'Criminal Justice', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (68, 'Dance', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (69, 'Earth Sciences', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (70, 'Eastern Philosophy', 5.5, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (71, 'Electrical Engineering', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (72, 'Entrepreneurship', 7, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (73, 'Fashion Design', 2, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (74, 'Film Studies', 1.5, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (75, 'Game Design', 3.5, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (76, 'Geophysics', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (77, 'Health Informatics', 4, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (78, 'Immunology', 7, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (79, 'Industrial Design', 2.5, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (80, 'Japanese Literature', 5.5, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (81, 'Labor Relations', 3, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (82, 'Marine Biology', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (83, 'Medical Physics', 4.5, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (84, 'Nanotechnology', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (85, 'Nuclear Engineering', 4, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (86, 'Oceanography', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (87, 'Petroleum Engineering', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (88, 'Public Health', 5.5, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (89, 'Real Estate', 4, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (90, 'Social Work', 3.5, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (91, 'Space Science', 7, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (92, 'Statistics', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (93, 'Textile Design', 4, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (94, 'Urban Sociology', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (95, 'Virology', 6, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (96, 'Water Resources Engineering', 4.5, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (97, 'Women’s Studies', 4, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (98, 'Zoology', 4, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (99, 'and Aerospace Studies', 2, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (100, 'Actuarial Science', 1.5, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (101, 'Anatomy', 4, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (102, 'Animal Behavior', 4, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (103, 'Arabic Language and Literature', 4, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (104, 'Architectural Engineering', 4, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (105, 'Asian Studies', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (106, 'Atmospheric Sciences', 4, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (107, 'Biblical Studies', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (108, 'Biostatistics', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (109, 'Business Analytics', 4, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (110, 'Celtic Studies', 4, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (111, 'Chiropractic', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (112, 'Cognitive Neuroscience', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (113, 'Comparative Literature', 4, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (114, 'Criminology', 4, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (115, 'Dermatology', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (116, 'Developmental Biology', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (117, 'Digital Communications', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (118, 'Early Childhood Education', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (119, 'Egyptology', 2, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (120, 'Emergency Management', 4, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (121, 'Film Production', 4, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (122, 'Forensic Psychology', 7, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (123, 'Gender Studies', 4, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (124, 'Genetics Counseling', 6, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (125, 'Geology', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (126, 'Global Health', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (127, 'Health Economics', 4.5, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (128, 'Horticulture', 5, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (129, 'Immunotherapy', 3, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (130, 'International Business', 4, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (131, 'Islamic Studies', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (132, 'Journalism Ethics', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (133, 'Kabbalah', 2.5, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (134, 'Latin American Studies', 3, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (135, 'Machine Learning', 4, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (136, 'Metaphysics', 3, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (137, 'Music Therapy', 3.5, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (138, 'Mycology', 4, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (139, 'Nanomedicine', 1.5, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (140, 'Neurosurgery', 2.5, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (141, 'Optometry', 4, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (142, 'Paleontology', 3.5, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (143, 'Pharmacology', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (144, 'Quantum Physics', 4, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (145, 'Restoration Ecology', 3.5, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (146, 'Sign Language Interpretation', 1.5, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (147, 'Sustainable Agriculture', 4, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (148, 'Toxicology', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (149, 'Urban Economics', 1.5, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (150, 'Veterinary Pathology', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (151, 'Wind Energy Engineering', 7, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (152, 'Acoustical Engineering', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (153, 'Advanced Materials Science', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (154, 'Astrobiology', 2, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (155, 'Behavioral Neuroscience', 3, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (156, 'Biophysics', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (157, 'Business Ethics', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (158, 'Cartography', 3.5, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (159, 'Clinical Psychology', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (160, 'Conservation Ecology', 2.5, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (161, 'Cryptography', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (162, 'Demography', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (163, 'Earthquake Engineering', 5, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (164, 'Ecological Engineering', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (165, 'Educational Psychology', 4, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (166, 'Endocrinology', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (167, 'Environmental Law', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (168, 'Ethnomusicology', 4, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (169, 'Food Science', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (170, 'Genetic Engineering', 4, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (171, 'Geospatial Science', 4, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (172, 'Hematology', 4, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (173, 'Human-Computer Interaction', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (174, 'Industrial Psychology', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (175, 'International Security', 2.5, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (176, 'Judaic Studies', 4, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (177, 'Landscape Architecture', 4, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (178, 'Maritime Law', 4, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (179, 'Medical Anthropology', 4, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (180, 'Medieval Studies', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (181, 'Molecular Genetics', 5.5, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (182, 'Neuroethology', 4, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (183, 'Ocean Engineering', 3, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (184, 'Parasitology', 2, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (185, 'Petroleum Geoscience', 7, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (186, 'Psycholinguistics', 7, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (187, 'Public Policy', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (188, 'Religious Studies', 3, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (189, 'Social Entrepreneurship', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (190, 'Soil Science', 2.5, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (191, 'Sports Medicine', 1.5, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (192, 'Structural Biology', 2.5, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (193, 'Theoretical Physics', 4, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (194, 'Urban Design', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (195, 'Veterinary Pharmacology', 5.5, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (196, 'Volcanology', 3, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (197, 'Wildlife Biology', 7, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (198, 'Yiddish Studies', 4, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (199, 'Zoogeography', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (200, 'and Zymology', 3, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (201, 'Agricultural Economics', 4, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (202, 'Algorithm Design', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (203, 'Animal Nutrition', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (204, 'Applied Physics', 7, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (205, 'Aquatic Biology', 4, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (206, 'Arabic Poetry', 3, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (207, 'Architectural History', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (208, 'Astrochemistry', 3.5, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (209, 'Atmospheric Chemistry', 4, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (210, 'Behavioral Pharmacology', 3, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (211, 'Bioinformatics', 4, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (212, 'Biomaterials', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (213, 'Business Intelligence', 1.5, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (214, 'Ceramic Engineering', 4, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (215, 'Child Development', 4, 3.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (216, 'Climate Policy', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (217, 'Clinical Neuropsychology', 3, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (218, 'Comparative Politics', 4, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (219, 'Computational Chemistry', 3, 5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (220, 'Conservation Genetics', 4, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (221, 'Corporate Strategy', 1.5, 4);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (222, 'Cultural Anthropology', 1.5, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (223, 'Developmental Neuroscience', 2.5, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (224, 'Digital Forensics', 2.5, 2);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (225, 'Earth System Science', 5.5, 3);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (226, 'Ecotoxicology', 4, 4.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (227, 'Energy Policy', 3, 2.5);
insert into courses (COURSE_NUMBER , NAME, credits, WEEKLY_HOURS) values (228, 'Environmental Ethics', 4, 3);
